name: Test Scripts (EOL)
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/test-scripts-eol.yml"
      - "ros-kinetic-**.sh"
      - "ros-melodic-**.sh"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/test-scripts-eol.yml"
      - "ros-kinetic-**.sh"
      - "ros-melodic-**.sh"
  schedule:
    - cron: "5 1 * * 6" # Weekly on Saturdays at 01:05(GMT)

jobs:
  # kinetic:
  #   runs-on: ubuntu-latest
  #   container: ubuntu:xenial
  #   strategy:
  #     matrix:
  #       package: [desktop, ros-base]
  #   env:
  #     ROS_DISTRO: kinetic
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Test
  #       run: |
  #         apt-get update
  #         DEBIAN_FRONTEND=noninteractive apt-get install -yq wget curl git build-essential vim sudo lsb-release locales bash-completion tzdata
  #         ./ros-${ROS_DISTRO}-${{ matrix.package }}.sh

  melodic:
    runs-on: ubuntu-latest
    container: ubuntu:bionic
    strategy:
      matrix:
        package: [desktop, ros-base]
    env:
      ROS_DISTRO: melodic
    steps:
      - name: Pre-install
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -yq wget curl git build-essential vim sudo lsb-release locales bash-completion tzdata libc6
          # Ubuntu 16/18 can't run Node 20, so stick to older actions: https://github.com/actions/checkout/issues/1590
          echo "GHA_USE_NODE_20=false" >> $GITHUB_ENV
          echo "ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Test
        run: |
          ./ros-${ROS_DISTRO}-${{ matrix.package }}-main.sh
