name: Test Scripts (EOL)
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/test-scripts-eol.yml"
      - "**.sh"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/test-scripts-eol.yml"
      - "**.sh"
  schedule:
    - cron: "5 1 * * 6" # Weekly on Saturdays at 01:05(GMT)

jobs:
  # kinetic:
  #   runs-on: ubuntu-latest
  #   container: ubuntu:xenial
  #   strategy:
  #     matrix:
  #       package: [desktop, ros-base]
  #   env:
  #     ROS_DISTRO: kinetic
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Test
  #       run: |
  #         apt-get update
  #         DEBIAN_FRONTEND=noninteractive apt-get install -yq wget curl git build-essential vim sudo lsb-release locales bash-completion tzdata
  #         ./ros-${ROS_DISTRO}-${{ matrix.package }}.sh

  melodic:
    runs-on: ubuntu-latest
    container: ubuntu:bionic
    strategy:
      matrix:
        package: [desktop, ros-base]
    env:
      ROS_DISTRO: melodic
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -yq wget curl git build-essential vim sudo lsb-release locales bash-completion tzdata
          ./ros-${ROS_DISTRO}-${{ matrix.package }}-main.sh
